@ECHO OFF

REM *** LOCAL TARGET PATHS and FILES
SET TIDDLYWIKI_RELEASE=
SET TIDDLYWIKI_PULLED=
SET TIDDLYWIKI_DEST=
SET TIDDLYWIKI_TEST=
SET TIDDLYWIKI5_DIR=

REM *** LOCAL UTILITY APPLICATIONS
SET CURL=
SET DIFF=
SET BROWSER=
