@ECHO OFF

REM *** LOCAL TARGET PATHS and FILES
SET RELEASE=
SET PULLED=
SET DEST=
SET TEST=
SET TW5=

REM *** REMOTE TARGET FOLDERS, FILES, and UPLOAD PARAMS
SET REMOTE_USER=
SET HOST=
SET DIR=
SET ARCHIVE_DIR=
SET OWNER=
SET PERM=
SET UPLOADLIST=

REM *** LOCAL UTILITY APPLICATIONS
SET CURL=
SET DIFF=
SET SCP=